# load libraries and data
```{r}
library(dplyr)
library(ggplot2)
library(sf)

# read in road data
# r <- read_sf("private_data/tl_2019_us_primaryroads.shp")

# read in county data
c <- read_sf("public_data/cb_2018_us_county_20m.shp")
c <- c[c$STATEFP %in% c("34","36", "42", "09"),] 
# https://www.mercercountypa.gov/dps/state_fips_code_listing.htm

# load all state boundaries
state_bounds <- 
  rnaturalearth::ne_states(returnclass = "sf", 
                           country = "United States of America")  %>%
  st_transform(crs = st_crs(c))

# get state boundaries just for northeast
ne <- state_bounds[state_bounds$region == "Northeast",]
```

# make a map
```{r}

# make a basic map of Northeast
ggplot() +
  geom_sf(aes(), fill = "lightgray", color = "darkgray", data = ne) +
  geom_sf(aes(), data = c, fill = "gray") +
  theme_bw()

ggsave("figures/northeast.png", height = 5, width = 5, dpi = 400)

```


# data sources
roads:
https://catalog.data.gov/dataset/tiger-line-shapefile-2019-nation-u-s-primary-roads-national-shapefile

counties:
https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html
